name: CI/CD

on:
  push:
    branches:
      - develop
      - main
      - BB-303-INFRA/DEVSECOPS-CI-CD
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DEV: true
      API_URL: ${{ secrets.API_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Generate env.ts file
        run: |
          echo "export const env = { API_URL: process.env.API_URL };" > src/configs/env/env.ts

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test --passWithNoTests
        continue-on-error: true

      - name: Verify CI pipeline
        run: echo "CI pipeline is successful"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    env:
      DEV: false
      API_URL: ${{ secrets.API_URL_PROD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate env.ts file
        run: |
          echo "export const env = { API_URL: process.env.API_URL };" > src/configs/env/env.ts

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Android App Bundle (AAB)
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
